[package]
name = "index3ds-frontend"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.8"
stdweb = "0.4"
index3ds-common = { path = "../common" }
serde = "1.0"
serde_urlencoded = "0.6"
